version = 0.1
[default.deploy.parameters]
stack_name = "TA-S3-Versioning"
resolve_s3 = true
s3_prefix = "TA-S3-Versioning"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
